Fix skip job logic

diff --git a/.github/workflows/forward-merge.yml b/.github/workflows/forward-merge.yml
--- a/.github/workflows/forward-merge.yml
+++ b/.github/workflows/forward-merge.yml
@@ -8,7 +8,7 @@ on:
       - prerelease/minor
 
 jobs:
-  test-ff-only:
+  get-branch-names:
     # Only run if:
     # - commit contains '[skip release]' (release commits or commits that skipped a release)
     # - branch is prerelease/minor
@@ -49,34 +49,40 @@ jobs:
         run: |
           echo ${{steps.extract-next-branch.outputs.branch}}
 
+  test-ff-only:
+    needs: ['get-branch-names']
+    runs-on: ubuntu-latest
+
+    steps:
       ## First, we'll checkout the repository. We don't persist credentials because we need a
       ## Personal Access Token to push on a branch that is protected. See
       ## https://github.com/cycjimmy/semantic-release-action#basic-usage
       - uses: actions/checkout@v3
         with:
           persist-credentials: false
-          ref: ${{steps.extract-next-branch.outputs.branch}} # checkout the next branch
+          ref: ${{needs.get-branch-names.outputs.next-branch}} # checkout the next branch
           fetch-depth: 0 # Needed to do merges
 
       ## Attempt to do a fast-forward-only merge. If this succeeds, there is no divergence
       ## between the branches and we do not need to retest. The commit has already been
       ## verified. If this line fails, it will trigger `verify-merge`
       - name: Test ff-only merge
-        run: git merge origin/${{ steps.extract-branch.outputs.branch }} --ff-only
+        run: git merge origin/${{ needs.get-branch-names.outputs.branch }} --ff-only
 
       ## If the previous step passed, push the verified commit directly to the next branch
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
           github_token: ${{ secrets.GH_RW_TOKEN }}
-          branch: refs/heads/${{ steps.extract-next-branch.outputs.branch }}
+          branch: refs/heads/${{ needs.get-branch-names.outputs.next-branch }}
 
   ## If the previous step failed, it means the fast-forward attempt failed. There is a
   ## divergence and we will need to merge the branches and verify everything works.
   verify-merge:
     runs-on: ubuntu-latest
     if: failure()
-    needs: ['test-ff-only']
+    needs: ['get-branch-names', 'test-ff-only']
+
     steps:
       ## First, we'll checkout the repository. We don't persist credentials because we need a
       ## Personal Access Token to push on a branch that is protected. See
@@ -137,7 +143,7 @@ jobs:
       #     storybookBuildDir: docs
       #     exitOnceUploaded: false
       #     exitZeroOnChanges: false
-      #     ignoreLastBuildOnBranch: ${{ needs.test-ff-only.outputs.next-branch }}
+      #     ignoreLastBuildOnBranch: ${{ needs.get-branch-names.outputs.next-branch }}
       #     debug: true
 
       - name: Start Server
@@ -157,15 +163,17 @@ jobs:
         uses: ad-m/github-push-action@master
         with:
           github_token: ${{ secrets.GH_RW_TOKEN }}
-          branch: refs/heads/${{ needs.test-ff-only.outputs.next-branch }}
+          branch: refs/heads/${{ needs.get-branch-names.outputs.next-branch }}
 
   ## If we get here, it means the branches are not fast-forward mergeable, OR the merge commit
   ## failed verification. We will need manual intervention, so we'll create a pull request to
   ## be verified by a person.
   make-pull-request:
     runs-on: ubuntu-latest
-    if: failure()
-    needs: ['test-ff-only', 'verify-merge']
+    # Run only if the verify-merge job failed. If the test-ff-only fails, but verify-merge passes, we should skip
+    if: failure() && needs.verify-merge.result == 'failure'
+    needs: ['get-branch-names', 'verify-merge']
+
     steps:
       ## If we've failed any previous step, we'll need to create a PR instead
       - uses: NicholasBoll/action-forward-merge-pr@main
@@ -184,10 +192,10 @@ jobs:
             The pull request should inform you of merge conflicts before you start if any.
             1. Run the following commands in your terminal. If this succeeds, skip step 2. The last command will run a script that tries to merge and resolve conflicts automatically.
                 ```
-                git branch -D merge/${{needs.test-ff-only.outputs.branch}}-into-${{ needs.test-ff-only.outputs.next-branch }} || true
+                git branch -D merge/${{needs.get-branch-names.outputs.branch}}-into-${{ needs.get-branch-names.outputs.next-branch }} || true
                 git fetch upstream
-                git checkout merge/${{needs.test-ff-only.outputs.branch}}-into-${{ needs.test-ff-only.outputs.next-branch }}
-                git pull upstream merge/${{needs.test-ff-only.outputs.branch}}-into-${{ needs.test-ff-only.outputs.next-branch }} -f
+                git checkout merge/${{needs.get-branch-names.outputs.branch}}-into-${{ needs.get-branch-names.outputs.next-branch }}
+                git pull upstream merge/${{needs.get-branch-names.outputs.branch}}-into-${{ needs.test-ff-only.outputs.next-branch }} -f
                 node utils/forward-merge.js
                 ```
             2. If the previous step succeeded, skip to step 3. Resolve conflicts manually. Then run the following.
